
require('dotenv').config();
const fs = require('fs-extra');
const path = require('path');

async function generateFromTemplate(meta) {
  // lightweight placeholder - integrate with OpenAI/Anthropic with API keys
  const templ = fs.readFileSync(path.join(__dirname, '../templates/basic.md'), 'utf8');
  const content = templ
    .replace('{{title}}', meta.title || 'Untitled')
    .replace('{{overview}}', meta.overview || 'Overview placeholder')
    .replace('{{features}}', (meta.features || []).join('\n- '))
    .replace('{{examples}}', meta.examples || 'Example usage here');
  await fs.outputFile(meta.output || './docs/README.md', content);
  console.log('Generated docs');
}

const meta = {
  title: 'Example package',
  overview: 'Autogenerated README skeleton',
  features: ['Auto README', 'API docs'],
  examples: 'npx ai-docs-writer generate'
};

generateFromTemplate(meta).catch(console.error);

templates/basic.md

(kept from earlier)

prompt-templates/README_PROMPT.txt

You are an assistant that produces technical README.md files. Follow this structure:
- Title
- Short description
- Getting started
- Usage examples
- API reference (endpoints)
- Configuration